version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./db/migrations:/flyway/sql
      - ./flyway.conf:/flyway/conf/flyway.conf
volumes:
  postgres_data: